### ISSUE TITLE
Code for RIR generation (at different sample rates)

### ISSUE THREAD

**Issue by csteinmetz1** [FrancoisGrondin/BIRD#2]
I was wondering if code is available to render RIRs instead of using the pre-rendered datasets. I am particularly interested in this to provide the ability to render RIRs at different sample rates.

**Comment by FrancoisGrondin** [comment]
@csteinmetz1 Yes there is some code in Matlab we used. Please email me with your contact info and I will send it to you :)

francois.grondin2@usherbrooke.ca
